baseURL = "https://muhammedadeltaha.github.io/"
title = "Mohamed Adel"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Hi🖐️, I'm Mohamed Adel"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Mohamed Adel's personal website"
keywords = "blog,developer,personal"
info = ["Machine Learning Engineer", "Software Engineer", "Math Enthusiast"]

# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Facebook"
icon = "fa-brands fa-facebook fa-2x"
weight = 1
url = "https://www.facebook.com/profile.php?id=100080844923855"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/mohamed-adel-taha-07a08b92c33/"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 3
url = "https://github.com/MuhammedAdelTaha/"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 4
url = "https://medium.com/@MuhammedAdell/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Articles"
weight = 2
url = "articles/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"